language: python

python:
  - 3.8

install:
  - pip install coverage pytest

script:
  - echo $PWD
  - python setup.py pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - dev