language: python

python:
  - 3.8

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install -r requirements.txt
  - pip install pytest-cov pytest
  - python setup.py install

script:
  - pytest --cov=./ --cov-report=xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
